### ISSUE TITLE
Schema timeout

### ISSUE THREAD

**Issue by johnsickels** [flagpolejs/flagpole#120]
The current test [here](https://github.com/flagpolejs/flagpole/blob/master/tests/src/api/itunes.ts) times out around the `.schema` method. It passes instantly if you leave that schema assertion off. Not sure why, I usually reference my schemas by string `"@itunes"` in the `schemas/` directory

Found an error

```
(node:91861) UnhandledPromiseRejectionWarning: Error: schema is invalid: data/properties/resultCount must be object,boolean
```

Does that mean each property needs to be defined like

```
const itunesApiSchema = {
  properties: {
    resultCount: { type: "number" },
```

Should I just let the new schema validator create a new schema and use that?

Either way, I think the bigger concern is this:

## Expected Behavior
If a schema is invalid, fail immediately

## Actual Behavior
30s timeout

**Comment by johnsickels** [comment]
Found an error
```
(node:91861) UnhandledPromiseRejectionWarning: Error: schema is invalid: data/properties/resultCount must be object,boolean
```

Does that mean each property needs to be defined like
```
const itunesApiSchema = {
  properties: {
    resultCount: { type: "number" },
```

Should I just let the new schema validator create a new schema and use that?

**Comment by johnsickels** [comment]
Either way, I think the bigger concern is this:

## Expected Behavior
If a schema is invalid, fail immediately

## Actual Behavior
30s timeout

**Comment by jasonbyrne** [comment]
Yes... in the previous iteration, Flagpole had a "shorthand" way to define schemas where you could do something like `resultCount: "number"` but this was a non-standard custom schema validator that I wrote, which was similar but not identical to JSON Schema.

If you're curious, that previous validator exists here:
https://www.npmjs.com/package/@flagpolejs/json-validator

But it is no longer used in Flagpole. We've standardized on a choice between JSON Schema and JTD formats.
