### ISSUE TITLE
Control of CLI Output

### ISSUE THREAD

**Issue by williamareynolds** [flagpolejs/flagpole#36]
Many test frameworks provide different output in different situations. Jest will only show failures by default when running many suites. When running a single suite, each test will be shown. It would be awesome if Flagpole could have some CLI options for controlling the Summary output at the end of a run. 

 

- [ ]  In the current output mode (passing tests are shown), a digest of failing tests is always shown at the bottom.

- [x] A CLI option hides output of passing suites and only failing suites are shown in the output. The digest would not be shown in this situation.

- [ ] By default, suites are silent unless they fail. A --verbose | -v CLI flag makes the successful suites print in the summary.

- [ ] --ci flag for running in a CI server like Jenkins or Circle. CLI output could be simplified to show a summary only, hiding many status lines that wouldn't appear in an interactive terminal.

One of these mechanisms would probably make it a lot easier to track down failing tests, which is the general goal for this issue. I'm happy to lend a hand writing a PR in exchange for a walk-through of the architecture.

**Comment by jasonbyrne** [comment]
Got the foundations of the verbosity settings and stuff in there. I am happy to show you around the codebase and accept your PRs to help continue to enhance and refactor it. I'm not hiding the spinner and other things like that which will be crucial for your needs.

So bring it on! Set some time on my calendar.

**Comment by johnsickels** [comment]
I was going to open a feature request ticket but I will chain onto this instead..

Currently volume level 10 provides failures only. I would like to request that Scenario Titles are printed along with them. Example: When running ten suites with a hundred scenarios it is difficult to identify a failing assertion's source:

![](https://files.slack.com/files-pri/T0YR8CPPV-F014KA7LCEA/screen_shot_2020-06-03_at_10.28.15_am.png)
