### ISSUE TITLE
Flagpole Global Install Gone Bad

### ISSUE THREAD

**Issue by jmcquillen09** [flagpolejs/flagpole#67]
Trying to install Flagpole globally results in weird error:

Refusing to delete /usr/local/bin/flagpole: ../lib/node_modules/flagpole/cli.js symlink target is not controlled by npm /usr/local/bin
npm ERR! File exists: /usr/local/bin/flagpole
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

Following the links given in the error ended with "no file exists". However installing at v2.5.25 did work.

Version originally being tried to install was 2.5.30

**Comment by jasonbyrne** [comment]
Did you ever figure this out? Almost seems like a permission issue.

**Comment by jasonbyrne** [comment]
@jmcquillen09  did you get this figured out?

**Comment by jmcquillen09** [comment]
@jasonbyrne went into my usr/local/lib and removed flagpole, then reinstalled it there. Then installed it globally outside of that file as well. And it is now working.
