### ISSUE TITLE
fillForm doesn't select, but doesn't error

### ISSUE THREAD

**Issue by johnsickels** [flagpolejs/flagpole#88]
## Steps to Repro

Use `fillForm` on a browser suite

Select an option from a drop down that doesn't exist

## Expected Behavior

Throw a warning or error

## Actual Behavior

Suite continues as if it accurately filled the form

**Comment by jasonbyrne** [comment]
This is definitely doable. So you expect it to actually THROW an error, rather than failing the assertion?

**Comment by johnsickels** [comment]
> This is definitely doable. So you expect it to actually THROW an error, rather than failing the assertion?

Either is fine. If it is silent, and the form changes later, we will not know and it is difficult to track down the error. Somewhere in between may be an optional warning? Not a failure, but at least an orange message. 

A thrown error would terminate that suite, right? Whereas a failed assertion would continue to run? What do you think?

**Comment by jasonbyrne** [comment]
Correct, a thrown error terminates

**Comment by jasonbyrne** [comment]
Released v2.5.44  with optional failure on form field not existing as requested
