### ISSUE TITLE
More volume levels

### ISSUE THREAD

**Issue by johnsickels** [flagpolejs/flagpole#89]
## Current Behavior

Standard volume level is 50

This gives a spinner in the CLI and all browser actions ( `click` `type`, etc... )

Set to 45 and spinner goes away ( good for test report in CI ), but we also lose browser actions

## Desired Behavior

I want to turn the spinner off, but keep the browser actions

Documentation on which volume level is which

**Comment by jasonbyrne** [comment]
This is the file that controls what shows up at what volume: 
https://github.com/flagpolejs/flagpole/blob/master/src/logging/verbosity.ts

**Comment by jasonbyrne** [comment]
Just pushed an update that will make those detail messages show but let you hide the spinner. just set to 49 or less and spinner goes away but those won't (once we publish a new version)
