### ISSUE TITLE
maxScenarioDuration too short

### ISSUE THREAD

**Issue by johnsickels** [flagpolejs/flagpole#91]
## Current Behavior

A suite will [timeout](https://github.com/flagpolejs/flagpole/blob/efb70800f3dc66dfb913ccd08839033e5a494442/src/suitetaskmanager.ts#L379-L394) once we reach [30s](https://github.com/flagpolejs/flagpole/blob/efb70800f3dc66dfb913ccd08839033e5a494442/src/suitetaskmanager.ts#L41).

## Desired Behavior

Only timeout on no action. Perhaps 10s without any activity? If not possible, perhaps we can make this value configurable in the `flagpole.json` or set it higher. We have long running suites timing out in Scorecard.

**Comment by johnsickels** [comment]
@jasonbyrne this is also a block for a Flagpole Cloud. Would you be ok if we increase this max timeout for now and revisit an inactivity timeout later?

**Comment by johnsickels** [comment]
I found the option:

```suite.setMaxScenarioDuration(60000)````

Less urgent now, but it's a little annoying to have this option in every suite.

Would be nice for an inactivity timeout, still

**Comment by jasonbyrne** [comment]
Inactivity timeout would be cool. I don't have time to look into creating that right now. I'd be fine if you wanted to add that as this as a setting in flagpole.json but we don't really have a settings block in there right now so you'd have to probably add that new concept which could open the door for overriding other defaults

**Comment by johnsickels** [comment]
> Inactivity timeout would be cool. I don't have time to look into creating that right now. I'd be fine if you wanted to add that as this as a setting in flagpole.json but we don't really have a settings block in there right now so you'd have to probably add that new concept which could open the door for overriding other defaults

Ok, we can close as a distant feature request and revisit later. 😀
