### ISSUE TITLE
MaxListenersExceededWarning even with limit set at 10 or below

### ISSUE THREAD

**Issue by FloDanny** [flagpolejs/flagpole#95]
Even with concurrency limit set a warning is given if the more than 10 suite.scenarios fire.  Increasing the max listener greater than 50 does not help either.  reducing sites to 10 or less in the example avoids the warning.

(node:33670) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
`const suite = flagpole('Smoke - Platform API').setConcurrencyLimit(5).setMaxScenarioDuration(60000);

sites.forEach((site) => {
    suite
        .scenario(`${site.name} - Run Vertical Smoke Test`, 'browser', browserOpts)
        .open('/')
        .next(async (context) => {
            context.assert(context.response.statusCode).equals(200);
        })`

**Comment by jasonbyrne** [comment]
This is an error happening outside of Flagpole that I need to dig into more. This issue from Puppeteer seems to have some relevant information and possible work arounds:
https://github.com/puppeteer/puppeteer/issues/594

**Comment by johnsickels** [comment]
Fixed by #96
